name: Fly.io Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl auth import <<< "$FLY_API_TOKEN"
    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
